# Generated by Django 5.2.11 on 2026-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
